# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=15)),
                ('mon_income', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='persons_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=2)),
                ('DOB', models.DateField(null=True)),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.House_hold')),
            ],
        ),
    ]
