# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='season_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('monsoon', 'monsoon'), ('rainy', 'rainy'), ('summer', 'summer'), ('winter', 'winter')], default='summer', max_length=20)),
                ('crop', models.CharField(choices=[('cotton', 'cotton'), ('groundnut', 'groundnut'), ('maize', 'maize'), ('paddy', 'paddy'), ('sugarcane', 'sugarcane'), ('turmeric', 'turmeric')], default='paddy', max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm_info')),
            ],
        ),
    ]
