# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_season_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='well_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=15)),
                ('depth_in_meters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Avg_wateryield', models.DecimalField(decimal_places=2, max_digits=8)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm_info')),
            ],
        ),
    ]
