# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farm_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_location',
            name='sequence_no',
            field=models.IntegerField(default=0),
        ),
    ]
