# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_auto_20170913_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm_info',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.house_hold'),
        ),
        migrations.AlterField(
            model_name='persons_info',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.house_hold'),
        ),
        migrations.AlterField(
            model_name='well_observation',
            name='date_of_observation',
            field=models.DateTimeField(null=True),
        ),
    ]
