# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_auto_20170913_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_hold',
            name='links',
            field=models.CharField(default='gfdxgh', max_length=50),
        ),
        migrations.AlterField(
            model_name='farm_info',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.house_hold'),
        ),
        migrations.AlterField(
            model_name='persons_info',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.house_hold'),
        ),
    ]
